spring:
  application:
    name: pre-project-2-3-1

  datasource:
    url: jdbc:postgresql://localhost:5432/java_test_con
    name: java_test_con
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  #  sql:
  #    init:
  #      mode: always

  jpa:
    properties:
      hibernate:
        default_schema: first_long_app_with_tolya
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        highlight_sql: true
        c3p0:
          min_size: 5
          max_size: 20
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
    user:
      name: admin
      password: admin123
      authorities: ADMIN



logging:
  level:
    org:
      springframework:
        security=TRACE:

custom:
  success-redirect:
    user-url: /users/*
    admin-url: /admin/users